/** Presentation-only catalog. Historical facts, IDs and simulation enum values stay unchanged. */
export const GAME_TEXT = [
  ['农场总览', 'Farm overview'], ['今日工作', 'Today'], ['作业排程', 'Operations'], ['生产单元', 'Production unit'], ['决策中心', 'Decision center'], ['经营管理', 'Management'],
  ['待决策', 'Open'], ['等待复查', 'Awaiting review'], ['等待下属汇报', 'Awaiting team proposal'], ['待你批准', 'Awaiting approval'], ['调查中', 'Investigating'], ['已排程', 'Scheduled'], ['已完成', 'Completed'], ['已处理', 'Resolved'], ['执行受阻', 'Blocked'], ['已取消', 'Cancelled'], ['已过期限', 'Expired'], ['当前有效', 'Current'], ['已过期', 'Stale'], ['尚无信息', 'No information'], ['无效', 'Invalid'],
  ['传感器', 'Sensor'], ['现场人员', 'Field team'], ['实验室', 'Laboratory'], ['现场检查', 'Field inspection'], ['报告', 'Report'], ['估计', 'Estimate'], ['水分胁迫', 'Water stress'], ['生长阶段', 'Growth stage'], ['病害压力', 'Disease pressure'], ['营养状态', 'Nutrient status'],
  ['灌溉', 'Irrigation'], ['设备维护', 'Maintenance'], ['采收', 'Harvest'], ['经理亲自巡查', 'Manager personal inspection'], ['人工补水', 'Manual watering'], ['喷施', 'Spraying'], ['设备维修', 'Equipment repair'], ['传感器迁移', 'Sensor relocation'], ['田间巡查', 'Field inspection'], ['系统灌溉', 'System irrigation'],
  ['农场经理', 'Farm manager'], ['农艺师', 'Agronomist'], ['灌溉主管', 'Irrigation supervisor'], ['田间主管', 'Cultivation supervisor'], ['维护负责人', 'Maintenance lead'], ['Sentinel 分析助手', 'Sentinel assistant'], ['依据现有证据', 'Use available evidence'], ['控制作物风险', 'Reduce crop risk'], ['考虑资源约束', 'Consider resource limits'], ['仍有信息不确定性', 'Information is uncertain'], ['下属', 'Team member'], ['作业', 'Operation'],
  ['蓄水池', 'Water reservoir'], ['田间班组 A', 'Field crew A'], ['滴灌设备', 'Irrigation rig'], ['维护人员', 'Maintenance staff'], ['营养生长期', 'Vegetative'], ['开花期', 'Flowering'], ['坐果期', 'Fruit development'], ['转熟期', 'Ripening'], ['采收期', 'Harvest preparation'],
  ['还没有送达的观测。你可以安排现场检查。', 'No observations have arrived. Schedule a field inspection.'], ['收起历史观测', 'Collapse observations'], ['查看全部', 'View all'], ['条观测', 'observations'], ['观测', 'Observed'], ['送达', 'Delivered'], ['可靠度', 'Reliability'],
  ['核对生产单元的现场情况，补充可用证据。', 'Check the unit in person to obtain reliable evidence.'], ['安排现场检查', 'Schedule field inspection'], ['计划日期', 'Planned date'], ['执行人员', 'Assigned staff'], ['检查理由', 'Inspection reason'], ['确认安排检查', 'Confirm inspection'],
  ['选择一个生产单元', 'Select a production unit'], ['点击地图上的地块，查看你已经获得的信息。', 'Select a unit on the map to review available information.'], ['信息不足', 'Insufficient information'], ['分区', 'Cluster'], ['已知生长阶段', 'Observed growth stage'], ['等待阶段报告', 'Awaiting stage report'], ['阶段报告', 'Stage report'], ['未知', 'Unknown'], ['暂无可用证据', 'No available evidence'], ['关联决策', 'Related decisions'], ['关联作业', 'Related operations'], ['最新已送达观测', 'Latest available observations'],
  ['你依据哪些证据？希望控制什么风险？', 'Which evidence informed your decision? Which risk are you addressing?'], ['先调查，再判断', 'Gather evidence first'], ['请下属提出方案', 'Request a team proposal'], ['延后复查', 'Review later'], ['暂不采取行动', 'Take no action'], ['截止', 'Deadline'], ['无固定截止日期', 'No fixed deadline'], ['关注：', 'Impact: '], ['水资源', 'Water resources'], ['品质', 'Quality'], ['人员', 'Staff'], ['设备', 'Equipment'], ['产量', 'Yield'], ['农场运营', 'Farm operations'], ['已过原定期限', 'Past original deadline'],
  ['证据与观点存在差异', 'Evidence and assessments differ'], ['基于已送达证据 · 置信度', 'Based on available evidence · Confidence'], ['查看决策证据', 'Review evidence'], ['条已送达观测', 'available observations'], ['正在准备建议', ' is preparing a proposal'], ['预计汇报', 'Proposal due'], ['待确认', 'To be confirmed'], ['。建议送达并获你批准后，才会安排执行。', '. Operations are scheduled only after the proposal arrives and you accept it.'], ['下属建议 · 规则生成', 'Team proposal · Rule generated'], ['的建议已送达', ' proposal has arrived'], ['采取建议行动', 'Accept recommended action'], ['引用', 'References'], ['条当时可用证据', 'pieces of evidence available at the time'], ['批准后的计划日期', 'Date after approval'],
  ['已进入经理判断', 'Manager review opened'], ['你的下一步', 'Your next step'], ['执行班组', 'Assigned crew'], ['使用方案默认人员', 'Use proposed staff'], ['计划占用', 'Planned allocation'], ['人员日', 'staff-days'], ['。资源容量与库存将在确认时校验。', '. Capacity and inventory are checked when you confirm.'], ['预计作业费用', 'Expected operating cost'], ['机会成本', 'Opportunity cost'], ['汇报对象', 'Delegate to'], ['下属依据自己掌握的证据提出方案，未经你批准不会执行。', 'The team proposes an action using available evidence. Your approval is required.'], ['复查日期', 'Review date'], ['确认', 'Confirm'], ['委派', 'Delegate'], ['选择', 'choice'], ['已记录的选择', 'Recorded choice'], ['未填写理由', 'No reason provided'], ['计划', 'Planned'], ['实际', 'Actual'], ['等待执行', 'Awaiting execution'], ['尚无产出', 'No output yet'], ['已发生费用', 'Actual cost'], ['水', 'Water'], ['样本', 'Samples'],
  ['产能偏差', 'Productivity variation'], ['执行延迟', 'Execution delay'], ['手动改期', 'Reschedule'], ['资源不可用', 'Resource unavailable'], ['资源冲突', 'Resource conflict'], ['可用性变化', 'Availability changed'], ['移动开销与资源用量', 'Travel overhead and resource use'], ['额外移动开销', 'Travel overhead'], ['人员日；已计入容量和费用。', 'staff-days; included in capacity and cost.'], ['新计划日期', 'New planned date'], ['确认改期', 'Confirm reschedule'],
  ['今天需要你关注', 'Today’s priorities'], ['当前没有待处理决策', 'No pending decisions'], ['先查看农场信息，安排必要的检查，或推进一天等待新的报告。', 'Review the farm, schedule needed inspections, or advance to await new reports.'], ['查看农场地图', 'View farm map'], ['今天送达的报告', 'Reports arriving today'], ['已知作业安排', 'Known operations'], ['查看排程', 'View schedule'], ['没有等待执行的作业。新的安排会出现在这里。', 'No operations await execution. New plans will appear here.'],
  ['已知安排时间线', 'Known schedule'], ['只显示已知计划、期限与预期窗口', 'Known plans, deadlines and expected windows only'], ['未来两周暂无已知安排。尚未发生的随机事件与未送达报告不会显示在这里。', 'No known plans for the next two weeks. Future events and undelivered reports stay hidden.'], ['决定行动', 'Decide now'], ['调查', 'Investigate'], ['批准方案', 'Accept proposal'], ['拒绝方案', 'Reject proposal'], ['不采取行动', 'Take no action'], ['作业改期', 'Reschedule operation'], ['自定义方案', 'Custom plan'], ['未填写文字理由', 'No written reason'], ['当时引用', 'Evidence referenced at the time:'], ['条证据 · 注意力', 'items · Attention'], ['当时的人员观点', 'Assessments at the time'], ['当时已送达的证据', 'Evidence available at the time'], ['无', 'None'], ['置信度', 'Confidence'],
  ['这一轮经营已经结束', 'Season completed'], ['决策与理由回顾', 'Decisions and rationale'], ['个节点', 'cases'], ['尚未记录玩家行动理由', 'No player rationale recorded'], ['条可用证据 · 作业', 'available items · Operations'], ['已记录后果', 'recorded outcomes'], ['展开行动审计记录', 'Expand action audit'], ['本场景使用示例训练参数；复盘展示证据、选择和实际结果，不评定唯一“正确答案”。', 'This scenario uses training parameters. The review records evidence, decisions and results without scoring a single correct answer.'],
  ['资源与人员', 'Resources and staff'], ['每日容量', 'Daily capacity'], ['今日可用比例', 'Available today'], ['库存资源', 'Inventory'], ['应急采购水资源', 'Purchase emergency water'], ['经营账目', 'Finance'], ['可用现金', 'Available cash'], ['已发生经营成本（含采购）', 'Operating costs including purchases'], ['预计收入', 'Forecast revenue'], ['预计收入是基于可用证据的估计，尚未形成销售到账，不等于实际利润。', 'Revenue is a forecast based on available evidence. It is neither received cash nor actual profit.'], ['查看资金流水', 'View ledger'], ['作业费用', 'Operating cost'], ['应急采购', 'Emergency purchase'], ['你的农场团队', 'Your farm team'], ['本地规则分析 · 依据可用证据提出建议', 'Local rule analysis · Uses available evidence'], ['可委派分析 · 方案需经理批准', 'Delegated assessment · Approval required'],
  ['本轮与存档', 'Session and save'], ['模拟时长', 'Season length'], ['本地存档', 'Local save'], ['自动保存已开启', 'Autosave enabled'], ['刷新浏览器会继续本机进度。相同 seed 配合相同的有序选择，可重复同一轮结果。', 'Reload to resume on this browser. The same seed and ordered decisions reproduce the same results.'], ['重新开始', 'Restart'], ['本阶段固定扮演农场经理。存档保存在此浏览器，清除网站数据会移除存档。', 'You play the farm manager. Saves are local to this browser and are removed if site data is cleared.'], ['推进到下一阶段', 'Advance to next phase'],
  ['确认应急采购水资源', 'Confirm emergency water purchase'], ['确认后将扣除现金并增加蓄水池库存。采购需要有足够现金，不会自动透支。', 'Confirmation debits cash and adds water to inventory. Sufficient cash is required.'], ['采购数量（m³）', 'Quantity (m³)'], ['单价', 'Unit price'], ['预计扣款', 'Expected payment'], ['取消', 'Cancel'], ['确认采购并付款', 'Confirm and pay'], ['重新开始这一轮', 'Restart this season'], ['确认后会替换当前本地存档。当前轮次的决策与作业将从初始状态重建。', 'Confirmation replaces the current local save and rebuilds the season from its initial state.'], ['相同 seed', 'Same seed'], ['指定新 seed', 'New seed'], ['新的 seed', 'New seed'], ['模拟时长（天）', 'Season length (days)'], ['保留当前进度', 'Keep current progress'], ['确认重新开始', 'Confirm restart'],
  ['暂时无法恢复这份存档', 'Unable to restore this save'], ['存档版本不兼容或数据损坏。当前存档仍被保留。', 'This save is incompatible or damaged. The original data has been retained.'], ['开始新的一轮会替换当前本地存档；你也可以暂时返回原有 Demo。', 'A new season will replace this save. You may return to the original demo instead.'], ['我确认替换这份存档并从头开始', 'I confirm replacing this save and starting over'], ['确认开始新的一轮', 'Start a new season'], ['返回原有 Demo', 'Return to original demo'],
  ['容量或库存不足', 'Insufficient capacity or inventory'], ['这项操作未被接受，请检查计划与资源。', 'This operation was rejected. Check the plan and resources.'], ['已推进到下一阶段，报告与作业状态已更新。', 'Phase advanced. Reports and operation status have been updated.'], ['新的一轮已开始。', 'A new season has started.'], ['操作已记录，进度已自动保存。', 'Action recorded and progress saved.'], ['农场试玩导航', 'Farm game navigation'], ['你来决定下一步', 'You decide the next step'], ['观察 · 决策 · 执行 · 复盘', 'Observe · Decide · Execute · Review'], ['农场经营', 'Farm management'], ['进度已保存', 'Progress saved'], ['仅本次会话保存', 'In-memory session only'], ['存档需要关注', 'Save needs attention'],
  ['看见农场，做出有依据的选择。', 'See the farm. Make informed decisions.'], ['每一步选择，都留下可以追溯的记录。', 'Every decision leaves an auditable record.'], ['已结束', 'Ended'], ['本轮已结束', 'Season ended'], ['经营资源', 'Farm resources'], ['费用按实际执行记账', 'Costs recorded on execution'], ['日容量不结转', 'Daily capacity does not carry over'], ['水资源库存', 'Water inventory'], ['关键资源', 'Critical resource'], ['用水与应急采购均可追溯', 'Water use and purchases are traceable'], ['经理注意力', 'Manager attention'], ['早会固定 −1 · 普通排程免费', 'Meeting −1 · Routine scheduling is free'], ['关闭提示', 'Dismiss notice'], ['天经营已完成', 'days completed'], ['查看财务、水资源、作业偏差与决策记录，复盘这一轮。', 'Review finance, water use, operation variations and decisions.'], ['查看经营复盘', 'View season review'], ['农场全景', 'Farm overview'], ['生产单元总览', 'Production units'], ['个单元', 'units'], ['玩家已知信息', 'Available information'],
  ['地图图层', 'Map layers'], ['水分与风险', 'Water and risk'], ['作业与决策', 'Tasks and decisions'], ['信息新鲜度', 'Information freshness'], ['分区筛选', 'Filter by cluster'], ['全部分区', 'All clusters'], ['品种筛选', 'Filter by variety'], ['全部品种', 'All varieties'], ['地图依据生产单元几何数据绘制', 'Map uses production-unit geometry'], ['灰色表示未知或过期信息', 'Grey indicates unknown or stale information'],
  ['决定什么时候行动，也决定先获得什么信息。', 'Decide when to act and which evidence to obtain first.'], ['不同角色可能基于不同来源形成观点。所有可见证据均已送达，计划仍需经过资源检查。', 'Roles may assess different sources. All displayed evidence is available, and plans still need resource checks.'], ['新的决策尚未出现', 'No new decisions yet'], ['推进时间，等待证据与场景事件。你也可以先在地图上检查生产单元。', 'Advance to await evidence and events, or inspect a unit first.'], ['计划与实际，放在一起看。', 'Compare planned and actual work.'], ['人员、设备和库存会在排程与执行时分别检查；受阻的作业可以手动改期。', 'Staff, equipment and inventory are checked at scheduling and execution. Blocked work can be rescheduled.'], ['按生产单元筛选', 'Filter by production unit'], ['全部生产单元', 'All production units'], ['还没有安排作业', 'No operations scheduled'], ['安排一次现场检查，或在决策中心选择可执行方案。', 'Schedule an inspection or select an actionable plan in the decision center.'], ['依据可见证据决策 · 本地自动保存', 'Decide using available evidence · Local autosave'],
  ['每天一次早会，把观察变成行动', 'One morning meeting turns observations into action'], ['是单独管理作物、供水和设备的生产单元。早上回顾昨日结果，判断风险，安排今天或未来的工作。', 'is a unit managed for crops, water and equipment. Review yesterday’s results, assess risk, and schedule today or future work.'], ['是班组当天的工作容量，不能结转；巡查也占用人力，所以无法每天检查所有单元。', 'is the crew’s daily capacity, which does not carry over. Inspections consume labor, so every unit cannot be inspected daily.'], ['是经理亲自判断和现场工作的认知资源。早会固定消耗 1，普通排程免费；复杂判断消耗 1，经理巡查消耗 2。', 'is the manager’s capacity for judgment and personal fieldwork. Meetings cost 1, routine scheduling is free, complex review costs 1 and personal inspection costs 2.'], ['表示信息可信度；', 'indicates information reliability;'], ['表示最新有效信息距今几天。传感器可更新水分信息，却不能代替作物与设备巡查。', 'is the age of the latest valid information. Sensors update water data but do not replace crop and equipment inspections.'], ['开始今天的早会', 'Start today’s meeting'], ['预计影响 · 次日正式更新', 'Expected impact · Confirmed next morning'], ['已有 Action:', 'Scheduled actions:'], ['最新 Crop + Equipment 巡查', 'Latest crop and equipment inspection'], ['复杂判断 · Attention −1', 'Complex review · Attention −1'],
  ['安排任务 · Today / Future Date', 'Schedule tasks · Today or a future date'], ['普通排程 Attention 0；Inspection 同时检查作物与设备。进入 Execution 后，新发现的问题留到次日早会处理。', 'Routine scheduling costs no attention. Inspections cover crops and equipment. New issues discovered during execution wait until the next morning meeting.'], ['日期', 'Date'], ['Labor · 执行班组', 'Labor · Assigned crew'], ['确认排程', 'Confirm schedule'], ['重复任务改期日期', 'Reschedule duplicate task'], ['排程窗口已关闭。Next Morning 再安排。', 'Scheduling is closed. Plan again next morning.'], ['Mobile Sensor 必须通过 Sensor Relocation 作业迁移（Labor 1）。水分传感器不能更新 Crop Freshness。', 'Move a mobile sensor through a relocation task (1 Labor). Water sensors cannot renew crop freshness.'], ['查看正式作业排程', 'View operations schedule'], ['查看观察日历', 'View observation calendar'],
  ['实线 = Estimate · 阴影 = Uncertainty Range。范围由来源、可信度、新鲜度和传感器覆盖推导；未知值不绘制。', 'Solid line = estimate; shading = uncertainty range, based on source, confidence, freshness and sensor coverage. Unknown values are not plotted.'], ['Crop Guide · 生长阶段与管理重点', 'Crop guide · Growth stages and priorities'], ['安排巡查或等待有效的生长阶段报告。', 'Schedule an inspection or await a valid growth-stage report.'], ['Decision History · Observation → Decision → Action → Result', 'Decision history · Observation → Decision → Action → Result'], ['推荐/决定：', 'Recommendation / decision:'], ['Optional — 未填写', 'Optional — Not provided'], ['输入信息与依据', 'Inputs and evidence'], ['普通任务与 Team / AI Assistant 决策将在这里记录。', 'Routine tasks and team / AI decisions are recorded here.'],
  ['Morning Meeting · 昨日反馈', 'Morning meeting · Yesterday’s feedback'], ['Execution · 今日反馈', 'Execution · Today’s feedback'], ['End of Day · 复盘', 'End of day · Review'], ['早会 Attention −1 已扣除。剩余', 'The meeting’s 1 Attention has been charged. Remaining:'], ['，已预留', ', reserved:'], ['。当前', '. Current phase:'], ['可排程 Today / Future Date', 'Schedule today or future work'], ['排程关闭，新问题留到 Next Morning', 'Scheduling closed; new issues wait until next morning'], ['次日结合天气、ET、生长阶段、设备与观测正式更新', 'Confirmed next morning using weather, evapotranspiration, growth stage, equipment and observations'], ['每日记录', 'Daily history'],
  ['未分区', 'Unassigned'], ['品种未登记', 'Unregistered variety'], ['项待办', 'pending tasks'], ['尚无水分观测', 'No water observations'], ['阶段待确认', 'Stage unconfirmed'], ['观测已过期', 'Observation is stale'], ['待观测', 'Awaiting observation'], ['水分信息新鲜度', 'Water information freshness'], ['个分区', 'clusters'], ['点击展开', 'Select to expand'], ['没有符合筛选条件的生产单元', 'No production units match the filters'], ['农场生产单元地图', 'Farm production-unit map'], ['地图缩放', 'Map zoom'], ['放大地图', 'Zoom in'], ['缩小地图', 'Zoom out'], ['显示整个农场', 'Show entire farm'], ['全图', 'Fit map'], ['示意地图 · 点击生产单元查看证据', 'Schematic map · Select a unit to review evidence'], ['地图图例', 'Map legend'], ['有待办', 'Pending tasks'], ['暂无待办', 'No pending tasks'], ['低风险', 'Low risk'], ['需关注', 'Needs attention'], ['高风险', 'High risk'], ['过期', 'Stale'], ['颜色依据已送达的信息', 'Colors use available information'],
  ['当天资源容量不足', 'Insufficient daily capacity'], ['资源库存不足', 'Insufficient inventory'], ['资源不支持该作业', 'Resource does not support this operation'], ['找不到所选资源', 'Selected resource not found'], ['今日管理注意力不足', 'Insufficient manager attention'], ['现金不足', 'Insufficient cash'], ['采购数量不符合限制', 'Purchase quantity outside limits'], ['本轮暂存于内存', 'Session held in memory'], ['浏览器无法读取存档，本轮暂存于内存', 'Save unavailable; session held in memory'], ['无法读取本地存档，本轮暂存于内存', 'Cannot read local save; session held in memory'], ['已恢复自动存档', 'Autosave restored'], ['。原存档已保留，选择重新开始后才会覆盖。', '. Original save retained until you confirm a restart.'], ['已自动保存', 'Autosaved'], ['自动存档失败，当前仍可试玩；刷新可能丢失本次进度', 'Autosave failed. You can continue, but reloading may lose progress.'], ['人员/设备日', 'staff/equipment-days'], ['需求', 'Required'], ['可用', 'Available'], ['请先处理存档提示', 'Resolve the save notice first'], ['操作未被接受', 'Action rejected'], ['试玩时长需为 1–365 个整数天', 'Season length must be an integer from 1 to 365 days'],
  ['经理巡查', 'Manager inspection'], ['工人', 'Worker'], ['巡查', 'Inspection'], ['阶段未知', 'Stage unknown'], ['尚无阶段报告', 'No stage report'], ['水分信息未知', 'Water information unknown'], ['水分胁迫估计', 'Estimated water stress'], ['经理综合', 'Manager synthesis of'], ['条可用观测', 'available observations'], ['（预计）', ' (expected)'], ['品种未知', 'Unknown variety'], ['风险未知', 'Unknown risk'], ['水分风险高', 'High water risk'], ['水分风险中', 'Moderate water risk'], ['水分风险低', 'Low water risk'], ['维护', 'Maintenance'], ['委派汇报', 'Delegated report'], ['复查', 'Review'], ['决策期限', 'Decision deadline'], ['配置的预期采收窗口开始（预期）', 'Configured harvest window starts (expected)'],
  ['财务状况', 'Financial position'], ['现金与已发生费用单独核对；预计收入并未实现。', 'Reconcile cash and actual costs separately; forecast revenue is unrealized.'], ['期末现金', 'Final cash'], ['已发生成本', 'Actual costs'], ['基于可用证据与示例品种参数，非实际利润', 'Based on available evidence and training variety parameters, not actual profit'], ['作物与信息覆盖', 'Crops and information coverage'], ['依据玩家已获得的观测和估计，未知信息保持未知。', 'Uses the player’s observations and estimates. Unknown information stays unknown.'], ['有水分信息的单元', 'Units with water information'], ['水分信息过期', 'Stale water information'], ['已知高水分风险', 'Known high water risk'], ['水资源使用', 'Water use'], ['核对库存、投入与实际作业产出；未灌溉的库存变化包含场景资源事件。', 'Reconcile stock, inputs and actual output. Other inventory changes include scenario events.'], ['剩余库存', 'Remaining stock'], ['灌溉投入', 'Water input'], ['实际施用', 'Water applied'], ['应急补水', 'Emergency water'], ['运营可靠性', 'Operational reliability'], ['作业完成、阻塞和延迟分开展示。', 'Completed, blocked and delayed operations are shown separately.'], ['完成 / 计划', 'Completed / planned'], ['仍阻塞', 'Still blocked'], ['发生延迟的作业', 'Operations with delays'], ['决策与审计', 'Decisions and audit'], ['保留当时可见证据、理由、批准记录和实际后果。', 'Retains evidence, rationale, approvals and actual outcomes at the time.'], ['已处理 / 决策', 'Resolved / decisions'], ['记录理由的行动', 'Actions with rationale'], ['巡查作业', 'Inspection operations'],
  // Original authored Phase 2 cases and their advice.
  ['占用班组四分之一天；执行后次日送达报告，当前不能看到结果。', 'Uses a quarter crew-day. The report arrives after execution; results are not yet known.'], ['下属依据已送达证据提出建议；汇报次日到达，由你批准后执行。', 'The team uses available evidence. The proposal arrives next day and requires your approval.'], ['保留问题，按你选择的复查日期提醒；错过期限记录在复盘中。', 'Keep the case open until your review date. Missed deadlines are recorded.'], ['记录理由，不采取行动', 'Record rationale and take no action'], ['关闭当前决策并保留理由；后续证据与结果可供复盘，不自动评判对错。', 'Close this case and retain its rationale. Later evidence and outcomes remain available for review.'],
  ['PU-03：传感器与现场报告不一致', 'PU-03: sensor and field reports disagree'], ['传感器报告明显水分胁迫，现场人员认为情况较轻。你可以先调查，也可以基于现有证据安排灌溉。', 'The sensor reports water stress while the field team sees mild symptoms. Investigate first or irrigate using available evidence.'], ['传感器报告严重胁迫；工人报告轻度胁迫。', 'The sensor reports severe stress; the worker reports mild stress.'], ['综合现场观察与实验室报告，再判断是否需要补水。', 'Combine field and laboratory evidence before deciding whether to water.'], ['传感器有异常信号，建议关注，但信号不是隐藏真值。', 'The sensor reports an anomaly. Investigate it; a signal is not hidden ground truth.'], ['给 PU-03 补水', 'Water PU-03'], ['调查后再决定', 'Investigate before deciding'], ['灌溉占用半天班组，可能挤占当天检查。', 'Irrigation uses half a crew-day and may displace inspections.'],
  ['PU-03：滴灌设备减速，先修还是绕开？', 'PU-03: irrigation slows down — repair or bypass?'], ['设备调度记录显示连续三天只有一半可用容量。维修可以恢复容量；人工补水绕过设备，但需要更多班组时间。', 'Equipment records show half capacity for three days. Repair restores capacity; manual watering bypasses equipment but uses more crew time.'], ['修复设备降低后续排程压力；人工补水可直接缓解当前已知水分风险。', 'Repair reduces future scheduling pressure. Manual watering can relieve current known water risk.'], ['维修使用独立维修人员；完成后恢复未来三天滴灌设备容量。', 'Repair uses separate maintenance staff and restores irrigation capacity for the next three days.'], ['若已送达观测仍提示胁迫，人工补水可绕开设备，但会占用更多班组。', 'If available evidence shows stress, manual watering bypasses the equipment but needs more crew capacity.'], ['安排阀门维修', 'Schedule valve repair'], ['维修人员半天，预计 ¥150；完成后恢复未来三天滴灌设备容量。', 'Half a maintenance-day, expected ¥150. Restores irrigation capacity for three days.'], ['绕过设备，人工补水', 'Bypass equipment with manual watering'], ['不使用滴灌设备；消耗 25 m³ 水和班组四分之三天，预计 ¥300。', 'No irrigation rig required. Uses 25 m³ water and three-quarters of a crew-day, expected ¥300.'], ['人工补水会挤占当天其他检查与灌溉。', 'Manual watering may displace inspections and irrigation.'], ['维修占用半天独立维修人员。', 'Repair uses half a separate maintenance-day.'],
  ['采收前：PU-01 与 PU-03 如何分配水和班组？', 'Before harvest: allocate water and labor to PU-01 or PU-03?'], ['水库调拨扣减本地 3000 m³ 配额后，两块地争用同一天的班组与设备。检查各自已知水分信息，决定集中补水或分配给两块地。', 'After a 3000 m³ reservoir transfer, two units compete for the same crew and equipment. Review their known water status and choose one unit or split water.'], ['优先早熟地块，还是优先已知风险较高的地块？同时安排两个四分之三天方案会超出一天容量。', 'Prioritize the earlier crop or the unit with higher known risk? Two three-quarter-day plans exceed daily capacity.'], ['阶段报告与水分报告各有采样和送达时间；过期报告不能当作当前状态。', 'Stage and water reports have separate sampling and delivery dates. Stale reports do not represent current conditions.'], ['建议根据已送达证据分配资源；预计收入只用于比较，不是已经获得的利润。', 'Allocate resources using available evidence. Forecast revenue is for comparison, not realized profit.'], ['优先给 PU-01 补水', 'Prioritize watering PU-01'], ['优先给 PU-03 补水', 'Prioritize watering PU-03'], ['给两块地分配补水', 'Split water across both units'], ['两地方案共用 80 m³ 水，每块地得到约一半实际产出。', 'The shared plan uses 80 m³ water; each unit receives roughly half the output.'], ['两地方案占满一天班组；当天无法再安排检查。', 'The shared plan uses a full crew-day, leaving no capacity for inspections.'], ['两个独立优先方案合计 1.5 天，会产生容量冲突。', 'The two separate plans require 1.5 crew-days, causing a capacity conflict.'],
];

/** English-first labels used by the new panels; each has a single-language rendering. */
export const GAME_LABELS = [
  ['Production Unit', '生产单元'], ['Water Stress', '水分胁迫'], ['Crop Status', '作物状态'], ['Confidence', '可信度'], ['Freshness', '新鲜度'], ['Equipment', '设备'], ['Sensors', '传感器'], ['Latest Observation', '最新观测'], ['Crop', '作物'], ['Reliability', '长期可靠度'], ['Observation Confidence', '观测可信度'], ['Water Freshness', '水分信息新鲜度'], ['Crop Freshness', '作物信息新鲜度'], ['Confidence Range', '可信区间'], ['Irrigation Equipment', '灌溉设备'], ['Information Freshness', '信息新鲜度'], ['Water Risk', '水分风险'],
  ['Manager Attention', '经理注意力'], ['Labor', '劳动力'], ['Morning Meeting', '早会'], ['Execution', '执行'], ['End of Day', '日终复盘'], ['Next Morning', '次日早会'], ['morning', '早会'], ['execution', '执行'], ['end_of_day', '日终复盘'], ['Today', '今天'], ['Future Date', '未来日期'], ['Table View', '状态表'], ['Spatial View', '空间视图'],
  ['Normal', '正常'], ['Warning', '轻微问题'], ['Significant issue', '显著问题'], ['Fault', '故障'], ['Unknown', '未知'], ['Manager', '经理'], ['Team', '团队'], ['AI Assistant', '智能助手'], ['Accept', '接受'], ['Reject', '拒绝'], ['View', '查看'], ['Reschedule', '改期'], ['Cancel', '取消'], ['Keep', '保留'], ['Fixed', '固定'], ['Mobile', '移动'], ['Soil Moisture', '土壤水分'], ['Mobile Sensor', '移动传感器'],
  ['Field Inspection', '田间巡查'], ['Manager Personal Inspection', '经理亲自巡查'], ['Irrigation', '系统灌溉'], ['Manual Watering', '人工补水'], ['Spraying', '喷施'], ['Equipment Repair', '设备维修'], ['Sensor Relocation', '传感器迁移'], ['Sensor Distribution', '传感器分布'], ['Observation Calendar', '观察日历'], ['Operations Schedule', '作业排程'], ['Type / ID', '类型／编号'], ['Location', '位置'], ['Status', '状态'], ['Last update', '最新更新时间'], ['Fixed / Mobile', '固定／移动'], ['Waiting for update', '等待更新'],
  ['Total Labor Required', '总劳动力需求'], ['Available Labor', '可用劳动力'], ['Already Scheduled', '已安排'], ['Remaining', '剩余'], ['Attention Required', '注意力需求'], ['Available', '可用'], ['Reserved', '已预留'], ['Water Available', '可用水量'], ['Resource Conflict', '资源冲突'], ['Decision Reason', '决策理由'], ['Optional', '可选'], ['From', '来源'], ['Mobile Sensor · From → selected Unit', '移动传感器 · 原位置 → 所选单元'],
  ['No Observation', '无观测'], ['Related Action', '关联作业'], ['Water Stress Trend', '水分胁迫趋势'], ['All Production Units', '全部生产单元'], ['Water Stress trend mode', '水分趋势模式'], ['Water Stress estimate and uncertainty range', '水分胁迫估计与可信区间'], ['estimate with confidence range', '估计及可信区间'], ['Date', '日期'], ['Crop Guide', '作物指南'], ['Water sensitivity', '水分敏感度'], ['Pest/disease sensitivity', '病虫害敏感度'], ['Important observations', '观察重点'], ['Typical priorities', '典型管理重点'], ['Stage Unknown', '阶段未知'],
  ['Decision History', '决策历史'], ['Observation', '观测'], ['Decision', '决策'], ['Action', '作业'], ['Result', '结果'], ['Decision Maker', '决策者'], ['Rationale', '理由'], ['Growth Stage', '生长阶段'], ['Weather', '天气'], ['Rain', '降雨'], ['Observation IDs', '观测编号'], ['Existing Schedule', '已有排程'], ['Defer', '延后'], ['None', '无'], ['Estimated Water Stress', '预计水分胁迫'], ['Efficiency', '效率'], ['Observed', '观测时间'],
  ['PRODUCTION UNIT', '生产单元'], ['YOUR PRIORITIES', '今日重点'], ['INCOMING REPORTS', '送达报告'], ['KNOWN PLANS / NEXT 14 DAYS', '已知安排／未来十四天'], ['SEASON REVIEW', '季末复盘'], ['RESOURCES', '资源'], ['FINANCIAL POSITION', '财务状况'], ['TEAM', '团队'], ['THIS PLAYTHROUGH', '本轮试玩'], ['EMERGENCY SUPPLY', '应急采购'], ['NEW PLAYTHROUGH', '新一轮试玩'], ['LOCAL SAVE', '本地存档'], ['FARM MANAGER', '农场经理'], ['YUNNAN BLUEBERRY / TRAINING SCENARIO', '云南蓝莓／训练场景'], ['FARM OVERVIEW', '农场总览'], ['PRODUCTION UNITS', '生产单元'], ['MAP', '总览'], ['TODAY', '今日'], ['OPERATIONS', '作业'], ['UNITS', '单元'], ['DECISIONS', '决策'], ['MANAGEMENT', '经营'], ['PHASE 2 · 试玩反馈更新', '第二阶段 · 试玩反馈更新', 'Phase 2 · Playtest update'], ['Sentinel Farm Simulation · 示例训练场景', 'Sentinel 农场经营 · 训练场景', 'Sentinel farm simulation · Training scenario'],
  ['Seed', '随机种子'], ['ET', '蒸散量'], ['N', '北'], ['Water', '水分'], ['Fresh', '新鲜度'], ['Equip', '设备'], ['training', '训练'],
];

export const GAME_MESSAGES = [
  ['Scheduling is only available during Morning Meeting.', '只能在早会排程。'], ['Choose a Production Unit.', '请选择生产单元。'], ['Choose Today or a remaining future date before season end.', '请选择今天或本季结束前的未来日期。'], ['Choose a supported action.', '请选择支持的作业。'], ['This role does not have personal inspection capability.', '当前角色不具备亲自巡查能力。'], ['A task cannot contain the same action twice.', '同一任务不能包含重复作业。'], ['This action is already scheduled for this Production Unit on this date.', '该生产单元在此日期已安排这项作业。'], ['Resource Conflict: insufficient Labor, Manager Attention, or reserved water.', '资源冲突：劳动力、经理注意力或可预留水量不足。'], ['Choose an operational Mobile Sensor.', '请选择可正常工作的移动传感器。'], ['This Mobile Sensor is already reserved on this date.', '此移动传感器在当天已被预留。'], ['Sensor is already at the destination.', '传感器已位于目标单元。'], ['Resource Conflict: assigned crew, equipment or inventory unavailable.', '资源冲突：执行班组、设备或库存不可用。'], ['Resource Conflict: insufficient cash for reserved operations.', '资源冲突：现金不足以支付已预留作业。'], ['Only unexecuted tasks can be rescheduled.', '只有尚未执行的任务可以改期。'], ['Adjust tasks at the next Morning Meeting.', '请在次日早会调整任务。'], ['Only unexecuted tasks can be cancelled.', '只有尚未执行的任务可以取消。'], ['Cancelled; no operation or observation produced.', '已取消；未执行作业，也未产生观测。'], ['Cancelled: Labor, Attention and reserved resources released.', '已取消：劳动力、注意力与预留资源已释放。'], ['Execution begins once after Morning Meeting.', '早会结束后只能开始一次执行。'], ['Resource Conflict: adjust today’s tasks before execution.', '资源冲突：请在执行前调整今日任务。'], ['Irrigation, valves, pipes and drippers restored. Long-term reliability unchanged.', '灌溉系统、阀门、管道和滴头已恢复；长期可靠度保持不变。'], ['Watering failed: unavailable water or irrigation equipment Fault.', '补水失败：水资源不足或灌溉设备故障。'], ['Spraying completed. Crop response will be checked by future observations.', '喷施已完成；后续观测将用于检查作物响应。'], ['Unaccepted recommendation expired. Review updated information before making a new decision.', '未接受的建议已失效，请根据最新信息重新判断。'], ['Decisions are made during Morning Meeting.', '请在早会做出决策。'], ['Unknown decision maker.', '未知决策者。'], ['Routine decisions can be scheduled directly without Attention.', '普通决策可以直接排程，无需额外消耗注意力。'], ['Attention exhausted. Delegate to Team or AI Assistant.', '注意力已用完，可交给团队或智能助手。'], ['Prioritize evidence when uncertain, then feasible risk reduction.', '信息不确定时优先获取证据，再采取可行措施降低风险。'], ['Existing schedule or limited resources: defer to next Morning Meeting.', '已有排程或资源限制：留到次日早会复查。'], ['Resolve at the next Morning Meeting.', '请在次日早会处理。'], ['Decision is unavailable.', '该决策当前不可用。'], ['Rejected; no action executed.', '已拒绝；未执行作业。'], ['No new action: review next morning.', '未安排新作业；次日早会复查。'],
  ['Crew selection must preserve required equipment and inventory', '更换班组时必须保留所需设备和库存'], ['Review date must be a remaining simulation day', '复查日期必须位于本季剩余日期内'], ['Proposal must leave time for approval before the simulation ends', '建议汇报必须为季末前审批留出时间'], ['Proposal is unavailable', '建议当前不可用'], ['Operation cannot be rescheduled', '该作业不能改期'], ['Purchase is unavailable or exceeds configured quantity', '当前不能采购，或采购量超过限制'], ['Unknown subordinate', '未知团队成员'], ['Choose an action with an operation', '请选择包含可执行作业的方案'], ['Unknown decision option', '未知决策方案'], ['Unknown decision action', '未知决策类型'], ['存档版本与当前试玩不兼容', '存档版本与当前试玩不兼容', 'The save version is incompatible with this game'], ['存档结构不完整', '存档结构不完整', 'The save is incomplete'], ['存档观测索引无效', '存档观测索引无效', 'The save observation index is invalid'],
];

export const GAME_MIXED = [
  ['田间巡查 Labor 1 · Attention 0，同时检查作物与设备；完整组合任务请进入作业排程。', '田间巡查消耗 1 劳动力、0 注意力，同时检查作物与设备；组合任务请进入作业排程。', 'Field inspection uses 1 Labor and no Attention, and checks crops and equipment. Schedule combined tasks in Operations.'],
  ['决策理由（Optional）', '决策理由（可选）', 'Decision reason (optional)'], ['Decision Reason（Optional）', '决策理由（可选）', 'Decision reason (optional)'], ['Accept 不消耗 Manager Attention，资源容量仍需校验。', '接受建议不消耗经理注意力，但仍需校验资源容量。', 'Accepting a proposal uses no manager attention. Resource capacity still needs to be checked.'], ['Accept · 批准并排程', '接受并排程', 'Accept and schedule'], ['Reject · 拒绝', '拒绝', 'Reject'], ['经理复杂判断 · Attention −1', '经理复杂判断 · 注意力 −1', 'Manager review · Attention −1'], ['Delegate to Team · 免费', '交给团队 · 不消耗注意力', 'Delegate to team · No attention cost'], ['Delegate to AI Assistant · 免费', '交给智能助手 · 不消耗注意力', 'Delegate to AI assistant · No attention cost'], ['普通排程 Attention 0；复杂判断在进入时消耗 1。', '普通排程不消耗注意力；进入复杂判断消耗 1。', 'Routine scheduling is free; opening complex review costs 1 Attention.'], ['排程免费 · Manager Decision Reason Optional', '排程免费 · 经理决策理由可选', 'Scheduling is free · Manager rationale is optional'], ['Keep（保留当前计划） ·', '保留当前计划 ·', 'Keep current plan ·'], ['Cancel · 取消并释放资源', '取消并释放资源', 'Cancel and release resources'], ['今日剩余 Labor', '今日剩余劳动力', 'Labor remaining today'], ['开始 Execution', '开始执行', 'Start execution'], ['进入 End of Day', '进入日终复盘', 'Review end of day'],
  ['Morning Meeting → Execution → End of Day → Next Morning · 当前', '早会 → 执行 → 日终复盘 → 次日早会 · 当前', 'Morning meeting → Execution → End of day → Next morning · Current:'], ['观察 → 判断风险 → 安排资源 → Execution → End of Day → Next Morning 复盘', '观察 → 判断风险 → 安排资源 → 执行 → 日终复盘 → 次日早会复查', 'Observe → Assess risk → Allocate resources → Execute → End-of-day review → Next morning'], ['已有 Action:', '已有作业：', 'Scheduled actions:'], ['最新 Crop + Equipment 巡查', '最新作物与设备巡查', 'Latest crop and equipment inspection'], ['复杂判断 · Attention −1', '复杂判断 · 注意力 −1', 'Complex review · Attention −1'], ['Delegate to', '交给', 'Delegate to'], ['安排任务 · Today / Future Date', '安排任务 · 今天或未来日期', 'Schedule tasks · Today or a future date'], ['Labor · 执行班组', '劳动力 · 执行班组', 'Labor · Assigned crew'], ['Mobile Sensor · From → selected Unit', '移动传感器 · 原位置 → 所选单元', 'Mobile sensor · From → Selected unit'], ['Crop Guide · 生长阶段与管理重点', '作物指南 · 生长阶段与管理重点', 'Crop guide · Growth stages and priorities'], ['Decision History · Observation → Decision → Action → Result', '决策历史 · 观测 → 决策 → 作业 → 结果', 'Decision history · Observation → Decision → Action → Result'], ['Morning Meeting · 昨日反馈', '早会 · 昨日反馈', 'Morning meeting · Yesterday’s feedback'], ['Execution · 今日反馈', '执行 · 今日反馈', 'Execution · Today’s feedback'], ['End of Day · 复盘', '日终复盘', 'End-of-day review'],
  ['请先完成 Execution 与 End of Day，再进入次日早会', '请先完成执行和日终复盘，再进入次日早会', 'Complete execution and the end-of-day review before the next morning'], ['只可在 Morning Meeting 决策', '只能在早会决策', 'Make decisions during the morning meeting'], ['复杂判断请先进入经理决策，或交给 Team / AI Assistant', '复杂判断请先进入经理决策，或交给团队／智能助手', 'Open manager review for complex decisions, or delegate to the team / AI assistant'], ['只可在 Morning Meeting 接受建议', '只能在早会接受建议', 'Accept proposals during the morning meeting'], ['只可在 Morning Meeting 拒绝建议', '只能在早会拒绝建议', 'Reject proposals during the morning meeting'], ['资源采购请在 Morning Meeting 安排', '请在早会安排资源采购', 'Purchase resources during the morning meeting'], ['请先进入 Execution', '请先进入执行阶段', 'Start execution first'], ['只可在早会进入复杂判断', '只能在早会进入复杂判断', 'Open complex review during the morning meeting'], ['决策不可用', '决策当前不可用', 'Decision unavailable'], ['Attention 已用完，仍可交给 Team / AI Assistant', '注意力已用完，仍可交给团队／智能助手', 'Attention exhausted; you can still delegate to the team / AI assistant'],
  ['云南蓝莓 28 天管理训练', '云南蓝莓二十八天管理训练', 'Yunnan blueberry: 28-day management training'], ['只可在早会进入复杂判断', '只能在早会进入复杂判断', 'Open complex review during the morning meeting'],
];

GAME_TEXT.push(
  ['界面语言', 'Interface language'], ['农', 'M'], ['蓝莓生产单元', 'Blueberry production unit'], ['注意力', 'Attention'], ['劳动力', 'Labor'], ['阶段', 'Stage'], ['长势', 'Growth'], ['作物', 'Crop'], ['决策理由', 'Decision reason'], ['推荐', 'Recommendation'], ['正常', 'Normal'], ['良好', 'Vigorous'], ['稳定', 'Steady'], ['无', 'None'], ['条', 'items'], ['项', 'items'], ['笔', 'entries'], ['天', 'days'], ['日', 'days'], ['第', 'Day'], ['月', '/'], ['点', 'points'], ['元', 'CNY'],
  ['只可在早会进入复杂判断', 'Open complex review only during the morning meeting'], ['没有当前水分估计，建议先检查以获得证据。', 'No current water estimate is available. Inspect first to obtain evidence.'], ['先获取可靠证据。', 'Obtain reliable evidence first.'], ['优先降低已知水分风险。', 'Prioritize reducing known water risk.'], ['依据已有证据与场景方案复查。', 'Review using available evidence and scenario plans.'], ['先进行现场检查', 'Inspect in the field first'], ['采用该行动方案', 'Use this action plan'], ['原 Phase 2 开场现场报告', 'Original Phase 2 opening field report'],
);
GAME_LABELS.push(
  ['Calendar detail', '日历详情'], ['Decision reason', '决策理由'], ['Growth', '长势'], ['Stage', '阶段'], ['existing tasks', '已有任务'], ['Labor remaining', '剩余劳动力'], ['scheduled actions', '已安排作业'], ['Soil moisture update', '土壤水分更新'], ['meeting', '早会'], ['Vegetative', '营养生长'], ['Flowering', '开花期'], ['Fruit Development', '果实发育'], ['Ripening', '成熟期'], ['Harvest Preparation', '采收准备'], ['Field crew A (example)', '田间班组 A（示例）'], ['Field crew A', '田间班组 A'], ['Sensor data', '传感器数据'], ['Sensor unavailable', '传感器不可用'],
);

GAME_TEXT.push(['现场班组 A', 'Field crew A']);

GAME_TEXT.push(['玩法简介', 'Game guide'], ['作物知识', 'Crop knowledge']);
GAME_LABELS.push(['GUIDE', '玩法'], ['KNOWLEDGE', '百科']);
