export const eventRules = [
  { id:'observation-conflict',name:'传感器与现场报告不一致',eligibleWindow:{startDay:4,endDay:7},conditions:[],baseProbability:0.6,
    modifiers:[],maxOccurrences:1,effects:[{type:'decision',templateId:'water-stress-pu03'}] },
  { id:'sensor-valve-anomaly',name:'滴灌阀门流量异常，设备连续三天减半',eligibleWindow:{startDay:6,endDay:12},conditions:[],baseProbability:0.55,
    modifiers:[],maxOccurrences:1,effects:[{type:'resource_availability',resourceId:'irrigation-rig',factor:0.5,durationDays:3},{type:'decision',templateId:'valve-disruption'}] },
  { id:'labor-disruption',name:'班组出勤减少',eligibleWindow:{startDay:10,endDay:17},conditions:[],baseProbability:0.2,
    modifiers:[],maxOccurrences:2,effects:[{type:'resource_availability',resourceId:'crew-a',factor:0.5}] },
  { id:'water-pressure',name:'旱天增加用水压力',eligibleWindow:{startDay:12,endDay:24},
    conditions:[{path:'world.weather.rainfall',operator:'lt',value:1}],baseProbability:0.35,
    modifiers:[{conditions:[{path:'crops.CROP-03.trueState.waterStress',operator:'gt',value:0.7}],multiplier:1.5}],maxOccurrences:3,
    effects:[{type:'resource_delta',resourceId:'water',amount:-120}] },
  { id:'pre-harvest-tradeoff',name:'采收前分配水与班组；水库调拨扣减本地配额',eligibleWindow:{startDay:20,endDay:24},
    conditions:[{path:'crops.CROP-01.stage',operator:'eq',value:'harvest'}],baseProbability:0.7,modifiers:[],maxOccurrences:1,
    effects:[{type:'resource_delta',resourceId:'water',amount:-3000},{type:'decision',templateId:'pre-harvest'}] },
];
